Capstone project
hopeforkoami/phoneDetailsMaster pull request #2
Opened 2023-01-12 17:19 UTC by hopeforkoami

This is the final Capstone project, in this project I fetch API data from the [Phone details API](https://phone-specs-api.azharimm.dev/) using Redux Toolkit, UI is built with React. Tests are written using Jest and React Testing Library.
In this branch I:

  - Fetch phone brands' data from the [API](https://phone-specs-api.azharimm.dev/)
  - Fetch brand's phones from the [API](https://phone-specs-api.azharimm.dev/)
  - Store API data using Redux Toolkit
  - Add filtering for brands
  - Write the tests
  - Deploy 
  - My pull request targets the dev branch of this [project](https://github.com/hopeforkoami/phoneDetailsMaster).
  
  
The demo video of the project can be found in the link below:
[See here](https://drive.google.com/file/d/1adBIgTWWxY36oFl3XamZKJhadqNJ3bnR/view?usp=sharing)

2023-01-12 18:40 UTC, fobadara requested changes
Hi @hopeforkoami, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Linter are passing
✅ Project looks professional

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 18:40 UTC, fobadara commented on README.old.md
> +Phone Details Master is a single page  web app that fetch the phone-specs-api
[REQUIRED] Kindly delete this Readme file. It is not serving any purpose

2023-01-12 18:40 UTC, fobadara commented on README.md
> +- [Demo video](https://drive.google.com/file/d/1adBIgTWWxY36oFl3XamZKJhadqNJ3bnR/view?usp=sharing)
[REQUIRED] Kindly record a video on loom or through any other tool that allows video play online. Videos saved on Google drive require extra setup and tools in order to be viewed

2023-01-12 18:40 UTC, fobadara commented on README.md
> +## 👥 Authors <a name="authors"></a>
[REQUIRED] Kindly make this singular since you are the only author

2023-01-12 18:40 UTC, fobadara commented on src/pages/Home.js
> +  </div>);
[REQUIRED] Kindly ensure that your design follows the template as much as possible. For example in the template, there is no space between the elements and on the sides. But you have spaces there.
![image](https://user-images.githubusercontent.com/62938735/212144127-b52eb30d-8af8-4a58-88c7-30138c78f8f6.png)

[REQUIRED]You also don't have the top section present in the template.


![image](https://user-images.githubusercontent.com/62938735/212150170-03708c32-475d-4db6-abe7-825f14e0336d.png)

[REQUIRED] Kindly ensure that the texts and icons are positioned just like it is in the template

2023-01-12 18:40 UTC, fobadara commented on src/pages/phonesList.js
> +};
[REQUIRED] Kindly ensure that the details page is arranged horizontally just like the one in the template with a top section containing your desired image. 
![image](https://user-images.githubusercontent.com/62938735/212150860-32bcac9b-1c2e-40fc-ad08-803025f56569.png)

2023-01-12 18:40 UTC, fobadara commented on src/components/Phone.js
> +        <img src={ShowIcon} alt="Show Icon" />
[REQUIRED] Whenever I click on the icon on the details page it takes me to an undefined page. I don't think this icon or the link is needed for the details page.

2023-01-13 11:22 UTC, fobadara requested changes
Hi @hopeforkoami, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.


 ## Highlights
✅ Linters are passing
✅ Implemented reviewer suggestions

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 11:22 UTC, fobadara commented on README.md
> +- [Demo video](https://pdm.nogdevhouse.com/capstonevideo.mp4)
[REQUIRED] Good job fixing the video but you did not highlight a piece of code that you are impressed with. Also kindly ensure that your video reflects the current changes. you ade to the site.

2023-01-13 12:13 UTC, omarsalem7 approved these changes
Hi @hopeforkoami 😊, 

# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/10xZU9b7JBx14s/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper description ✔️
- The project has met all the technical aspects you needed for this project. Keep rocking!  ✔️


Cheers and Happy coding!👏👏👏

## Optional suggestions

- [ ] [OPTIONAL] Kindly fix the broken MIT license link and add your own license.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 12:13 UTC, merged